theo::decomp::symbol_t Class Reference
symbol_t is an abstraction upon the coff symbol. this allows for easier manipulation of the symbol. symbols can be different things, sections, functions, and even instructions (when functions are broken down).
#include `symbol.hpp`
Public Member Functions
symbol_t (coff::image_t *img, std::string name, std::uintptr_t offset, std::vector< std::uint8_t > data, coff::section_header_t *scn={}, coff::symbol_t *sym={}, std::vector< recomp::reloc_t > relocs={}, sym_type_t dcmp_type={})
the explicit constructor of this symbol.
std::string name () const
gets the name of the symbol.
std::uintptr_t offset () const
gets the offset into the section where the symbol is located.
std::uintptr_t allocated_at () const
returns the address where the symbol is allocated.
std::uint32_t size () const
returns the size of the symbol.
coff::section_header_t * scn () const
gets the section header of the section in which the symbol is contained.
coff::image_t * img () const
gets the imagine in which the symbol is located inside of.
std::vector< std::uint8_t > & data ()
returns a vector by reference of bytes containing the data of the symbol.
coff::symbol_t * sym () const
returns a pointer to the coff symbol object.
sym_type_t type () const
returns the type of the symbol.
std::vector< recomp::reloc_t > & relocs ()
returns a vector of relocations.
void allocated_at (std::uintptr_t allocated_at)
set the address where the symbol is allocated at.
std::size_t hash ()
gets the hash of the symbol name.
Static Public Member Functions
static std::size_t hash (const std::string &sym)
generate a hash given the name of the symbol.
static std::string name (const coff::image_t *img, coff::symbol_t *sym)
get the name of a symbol. this function will create a symbol name if the symbol is opaquely named.
Detailed Description
symbol_t is an abstraction upon the coff symbol. this allows for easier manipulation of the symbol. symbols can be different things, sections, functions, and even instructions (when functions are broken down).
this class is used throughout theodosius and is a keystone of the project. ensure you understand how this class works and what it contains.
Definition at line 59 of file symbol.hpp.
Constructor & Destructor Documentation
symbol_t()
theo::decomp::symbol_t::symbol_t (coff::image_t * img, std::string name, std::uintptr_t offset, std::vector< std::uint8_t > data, coff::section_header_t * scn = {}, coff::symbol_t * sym = {}, std::vector< recomp::reloc_t > relocs = {}, sym_type_t dcmp_type = {}) [explicit]
the explicit constructor of this symbol.
Parameters
img the image in which the symbol is located in.
name the name of the symbol.
offset offset into the section where this symbol is located.
data the data of the symbol. there can be no data.
scn the section header describing the section which contains the symbol.
sym the coff symbol itself.
relocs a vector of relocations this symbol has (if any).
dcmp_type the type of symbol
Definition at line 34 of file symbol.cpp.
    : m_name(name),
      m_offset(offset),
      m_data(data),
      m_scn(scn),
      m_relocs(relocs),
      m_sym_type(dcmp_type),
      m_sym(sym),
      m_img(img),
      m_allocated_at(0) {}
Member Function Documentation
allocated_at() [1/2]
std::uintptr_t theo::decomp::symbol_t::allocated_at () const
returns the address where the symbol is allocated.
Returns
the address where the symbol is allocated.
Definition at line 60 of file symbol.cpp.
                                          {
  return m_allocated_at;
}
Referenced by allocated_at(), and theo::recomp::recomp_t::copy_syms().
allocated_at() [2/2]
void theo::decomp::symbol_t::allocated_at (std::uintptr_t allocated_at)
set the address where the symbol is allocated at.
Parameters
allocated_at where the symbol is allocated at.
Definition at line 84 of file symbol.cpp.
                                                     {
  m_allocated_at = allocated_at;
}
References allocated_at().
data()
std::vector< std::uint8_t > & theo::decomp::symbol_t::data ()
returns a vector by reference of bytes containing the data of the symbol.
Returns
a vector by reference of bytes containing the data of the symbol.
Definition at line 76 of file symbol.cpp.
                                      {
  return m_data;
}
Referenced by theo::recomp::recomp_t::copy_syms(), theo::recomp::recomp_t::resolve(), theo::obf::jcc_rewrite_pass_t::run(), theo::obf::next_inst_pass_t::run(), and theo::obf::reloc_transform_pass_t::run().
hash() [1/2]
std::size_t theo::decomp::symbol_t::hash ()
gets the hash of the symbol name.
Returns
the hash of the symbol name.
Definition at line 88 of file symbol.cpp.
                         {
  return hash(m_name);
}
References hash().
Referenced by theo::decomp::routine_t::decompose(), hash(), theo::recomp::symbol_table_t::put_symbol(), theo::recomp::recomp_t::resolve(), theo::theo_t::resolve(), theo::obf::hello_world_pass_t::run(), and theo::obf::jcc_rewrite_pass_t::run().
hash() [2/2]
std::size_t theo::decomp::symbol_t::hash (const std::string & sym) [static]
generate a hash given the name of the symbol.
Parameters
sym the symbol name to create a hash from.
Returns
the symbol name hash
Definition at line 100 of file symbol.cpp.
                                             {
  return std::hash<std::string>{}(sym);
}
References sym().
img()
coff::image_t * theo::decomp::symbol_t::img () const
gets the imagine in which the symbol is located inside of.
Returns
the imagine in which the symbol is located inside of.
Definition at line 68 of file symbol.cpp.
                                 {
  return m_img;
}
Referenced by name(), and theo::obf::jcc_rewrite_pass_t::run().
name() [1/2]
std::string theo::decomp::symbol_t::name () const
gets the name of the symbol.
Returns
the name of the symbol.
Definition at line 52 of file symbol.cpp.
                               {
  return m_name;
}
Referenced by theo::decomp::routine_t::decompose(), theo::recomp::recomp_t::resolve(), theo::obf::hello_world_pass_t::run(), and theo::obf::reloc_transform_pass_t::run().
name() [2/2]
std::string theo::decomp::symbol_t::name (const coff::image_t * img, coff::symbol_t * sym) [static]
get the name of a symbol. this function will create a symbol name if the symbol is opaquely named.
for example in c++ if you define something like this:
some_struct_t val = { value_one, value_two };
`val` will be stored in the .data section of the coff file. however the symbol name will be opaque (the name of the symbol will be `.data`). this causes issues with theo since each symbol needs its own unqiue name to generate a unique symbol name hash. for symbols like this, theo will create a name for it with the following format:
.data::section_index!coff_file_timestamp+offset_into_section
Parameters
img the coff file containing the symbol.
sym the coff symbol itself.
Returns
the name of the symbol, or a created one.
Definition at line 104 of file symbol.cpp.
                                                                  {
  if (sym->has_section() &&
      sym->storage_class == coff::storage_class_id::private_symbol &&
      sym->derived_type == coff::derived_type_id::none) {
    auto scn = img->get_section(sym->section_index - 1);
    auto res = std::string(scn->name.to_string(img->get_strings()).data())
                   .append("#")
                   .append(std::to_string(sym->section_index))
                   .append("!")
                   .append(std::to_string(img->file_header.timedate_stamp))
                   .append("+")
                   .append(std::to_string(sym->value));
    return res;
  }
  return std::string(sym->name.to_string(img->get_strings()));
}
References img(), scn(), and sym().
offset()
std::uintptr_t theo::decomp::symbol_t::offset () const
gets the offset into the section where the symbol is located.
Returns
the offset into the section where the symbol is located.
Definition at line 56 of file symbol.cpp.
                                    {
  return m_offset;
}
Referenced by theo::obf::jcc_rewrite_pass_t::run().
relocs()
std::vector< recomp::reloc_t > & theo::decomp::symbol_t::relocs ()
returns a vector of relocations.
Returns
a vector of relocations.
Definition at line 96 of file symbol.cpp.
                                           {
  return m_relocs;
}
Referenced by theo::recomp::recomp_t::resolve(), and theo::obf::jcc_rewrite_pass_t::run().
scn()
coff::section_header_t * theo::decomp::symbol_t::scn () const
gets the section header of the section in which the symbol is contained.
Returns
the section header of the section in which the symbol is contained.
Definition at line 64 of file symbol.cpp.
                                          {
  return m_scn;
}
Referenced by name(), and theo::recomp::recomp_t::resolve().
size()
std::uint32_t theo::decomp::symbol_t::size () const
returns the size of the symbol.
Returns
the size of the symbol.
Definition at line 72 of file symbol.cpp.
                                 {
  return m_data.size();
}
sym()
coff::symbol_t * theo::decomp::symbol_t::sym () const
returns a pointer to the coff symbol object.
Returns
a pointer to the coff symbol object.
Definition at line 92 of file symbol.cpp.
                                  {
  return m_sym;
}
Referenced by hash(), name(), and theo::obf::jcc_rewrite_pass_t::run().
type()
sym_type_t theo::decomp::symbol_t::type () const
returns the type of the symbol.
Returns
the type of the symbol.
Definition at line 80 of file symbol.cpp.
                                {
  return m_sym_type;
}
Referenced by theo::recomp::recomp_t::allocate(), and theo::recomp::recomp_t::resolve().
The documentation for this class was generated from the following files:
include/decomp/symbol.hpp
src/decomp/symbol.cpp