theo::obf::hello_world_pass_t Class Reference
hello world pass example of how to inherit pass_t.
#include `hello_world_pass.hpp`
Public Member Functions
void run (decomp::symbol_t *sym)
virtual method which must be implimented by the pass that inherits this class.
Static Public Member Functions
static hello_world_pass_t * get ()
Detailed Description
hello world pass example of how to inherit pass_t.
Definition at line 39 of file hello_world_pass.hpp.
Member Function Documentation
get()
static hello_world_pass_t * theo::obf::hello_world_pass_t::get () [inline], [static]
Definition at line 45 of file hello_world_pass.hpp.
                                   {
    static hello_world_pass_t obj;
    return &obj;
  }
Referenced by main().
run()
void theo::obf::hello_world_pass_t::run (decomp::symbol_t * sym) [inline], [virtual]
virtual method which must be implimented by the pass that inherits this class.
Parameters
sym a symbol of the same type of m_sym_type.
Implements theo::obf::pass_t.
Definition at line 50 of file hello_world_pass.hpp.
                                {
    spdlog::info("[hello_world_pass_t] symbol name: {}, symbol hash: {}",
                 sym->name(), sym->hash());
  }
References theo::decomp::symbol_t::hash(), and theo::decomp::symbol_t::name().
The documentation for this class was generated from the following file:
examples/demo/hello_world_pass.hpp